### ISSUE TITLE
Issues with links inside content element body

### ISSUE THREAD

**Issue by webian** [FriendsOfTYPO3/frontend_editing#220]
Steps to reproduce:
1. make a link in text while inline editing (using modal link browser)
2. double click the link
    here modal link browser opens with possibility to remove the link
    ![](https://i.imgur.com/aFYqp7S.jpg)
3. save the editing
4. double click the link again
    here modal link browser opens but without the possibility to remove the link

To remove the link the editor have to exactly select the text of the link (ending space included).

Another related weird behaviour is that, if we create another link without saving, now is possible to remove the link created in the previous steps simply using the CKEditor remove link button ![](https://i.imgur.com/Od6pVeA.jpg).

This also happens if we leave the cursor inside the link text and switch window (ALT+TAB in Windows) and come back to the frontend editing window to find that the "CKEditor remove link button" is enabled.

**Comment by webian** [comment]
I found out that the Link Browser displays the "Remove link" option before the save because at that moment the link is in linkHandler format `t3://page?uid=35` and this is the right situation.

Unluckily after the save of the page obviously the link is rendered as a frontend link `/index.php?id=35` then the Link Browser, that expect a linkHandler format, can't parse the link correctly.

A solution could be to render the links in linkHandler format while in Frontend Editing mode.

**Comment by webian** [comment]
Related to this issue, it happens that when we edit a text with an already saved link then an uncaught TYPO3 Exception is thrown on save:
```
#1460629247: No valid handlers found for type: unknown
TYPO3\CMS\Core\LinkHandling\Exception\UnknownLinkHandlerException thrown in file
typo3/sysext/core/Classes/LinkHandling/LinkService.php in line 154.
```

**Comment by codesource** [comment]
I can't reproduce the bug. 
Several bugs have since been corrected on the editor CKE.

Is it still relevant?

**Comment by MattiasNilsson** [comment]
This have been solved in later version of the CKEditor and the issue can now be closed.

**Comment by gessulatgessulat** [comment]
We still have this bug within the latest TYPO3 8.7.7 + CKEditor version if try to create an relative link with the link module. Same errormessage: 

#1460629247: No valid handlers found for type: unknown
TYPO3\CMS\Core\LinkHandling\Exception\UnknownLinkHandlerException thrown in file
typo3/sysext/core/Classes/LinkHandling/LinkService.php in line 154.

**Comment by webian** [comment]
@MattiasNilsson @codesource I confirm that this issue is still present.
I also can't imagine how you can't reproduce this. Did you save the edit?
Because the bug appears after save, when the page is reloaded.

**Comment by robsonrobi** [comment]
Any news here ?

**Comment by griesi007** [comment]
The issus is still present in 8.7.9

**Comment by mmasmoudi** [comment]
I have the same error, i try to save a text content element with a link inside.

**Comment by nom10s** [comment]
Still present in 8.7.10, but it seems related to the core / CKEditor: TYPO3 crashes reproducible when trying to save this code in CKEditor.

<a href="/some-absolute-link/">Linktext</a> 

Saving this code in a HTML content element works fine.

**Comment by lorenzulrich** [comment]
Still present in 8.7.12

**Comment by devtroll** [comment]
Still present in 8.7.13

**Comment by devtroll** [comment]
Status? This is a blocker. You're plugin is not usable!

**Comment by devtroll** [comment]
To work around this problem, I created a hook that corrects the link before saving, so that this error message no longer appears. Anyone interested? Then I create a GIST from it.

**Comment by lorenzulrich** [comment]
> To work around this problem, I created a hook that corrects the link before saving, so that this error message no longer appears. Anyone interested? Then I create a GIST from it.

Here :-) Thanks!

**Comment by MattiasNilsson** [comment]
@devtroll Can you provide your hook? So I have something to start with.

**Comment by MattiasNilsson** [comment]
ping @devtroll

**Comment by devtroll** [comment]
Here you will find the code snippet: https://bitbucket.org/snippets/scw_bihlmaier/5ezpaB

**Comment by stiffelstuff** [comment]
Thanks @devtroll for the workaround!

**Comment by mabolek** [comment]
@ghost @devtroll @lorenzulrich I have spent a lot of time trying to reproduce your issue in TYPO3 8.7.24, but it really seems to be impossible. 

Please check the attached gif animation. Am I repeating the steps correctly?

![frontend_editing_issue_220](https://user-images.githubusercontent.com/8200271/57850363-0d3c2000-77de-11e9-9aa2-943e5c6481d1.gif)

**Comment by mabolek** [comment]
I am closing this ticket as no further information has been provided.
