### ISSUE TITLE
News detail view - cHash comparison failed

### ISSUE THREAD

**Issue by abvdveen** [FriendsOfTYPO3/frontend_editing#473]
If I visit a detail news page, when logged in in BE and frontend_editing enabled, I get a 
'Page Not Found - The page did not exist or was inaccessible. Reason: Request parameters could not be validated (&cHash comparison failed)' error.

Visiting the same page in another browser, where I'm not logged in gives the correct page.

#307 perhaps related?

**Comment by MattiasNilsson** [comment]
@abvdveen This is solved with the latest release done today! https://github.com/FriendsOfTYPO3/frontend_editing/releases/tag/1.9.8

**Comment by abvdveen** [comment]
@MattiasNilsson This is not solved, have 1.9.9 installed, same error.

**Comment by abvdveen** [comment]
@MattiasNilsson Probably some caching issue on my side, see also #484 - so seems to be fixed.

**Comment by MattiasNilsson** [comment]
@abvdveen Ok no worries and great that it works 👍
