### ISSUE TITLE
frontend_editing 3.1.3 - PHP Warning: Undefined array key "host"

### ISSUE THREAD

**Issue by stpink** [FriendsOfTYPO3/frontend_editing#669]
"I am working with TYPO3 11.5.30 and using the extension t3sbootstrap. FrontendEditing is installed, but I am unable to enable either the frontend or inline editing. Additionally, I am receiving the following error message in the admin log output:

Core: Error handler (BE): PHP Warning: Undefined array key "host" in /html/typo3-11/typo3conf/ext/frontend_editing/Classes/Controller/FrontendEditingModuleController.php line 386"

**Comment by MattiasNilsson** [comment]
@stpink Which version of Frontend editing are you using?

**Comment by stpink** [comment]
It's frontend_editing 3.1.3

**Comment by MattiasNilsson** [comment]
Try to update to the latest version we released today: https://github.com/FriendsOfTYPO3/frontend_editing/releases/tag/3.1.4

**Comment by stpink** [comment]
![image](https://github.com/FriendsOfTYPO3/frontend_editing/assets/93609420/a2120f08-fb39-4c73-b3d3-3994602a820d)
Thanks for the new version.
Unfortunately, it did not solve the problem.

**Comment by MattiasNilsson** [comment]
@stpink Try this new release: https://github.com/FriendsOfTYPO3/frontend_editing/releases/tag/3.1.5
